============================= test session starts =============================
platform win32 -- Python 3.12.9, pytest-8.3.5, pluggy-1.5.0 -- D:\ProgramaþÒo\Bybit_Watcher\venv\Scripts\python.exe
cachedir: .pytest_cache
rootdir: D:\ProgramaþÒo\Bybit_Watcher
collecting ... collected 0 items / 1 error

=================================== ERRORS ====================================
________________ ERROR collecting tests/test_schema_manager.py ________________
tests\test_schema_manager.py:9: in <module>
    from utils.schema_manager import SchemaManager
utils\schema_manager.py:7: in <module>
    from utils.logging_config import get_banco_logger
utils\logging_config.py:56: in <module>
    from utils.handlers import get_banco_handler
utils\handlers.py:5: in <module>
    logger = get_logger(__name__)
E   NameError: name 'get_logger' is not defined
=========================== short test summary info ===========================
ERROR tests/test_schema_manager.py - NameError: name 'get_logger' is not defined
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 error in 0.26s ===============================
